GET http://localhost:8880/ebook/list
###
GET http://localhost:8880/ebook/list?name=Spring
###
GET http://localhost:8880/ebook/list?page=2&size=2
###
GET http://localhost:8880/ebook/list?page=1&size=1001

###

POST http://localhost:8880/ebook/save
Content-Type: application/json

{}

###

POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
#/delete/{idsStr}
DELETE http://localhost:8880/doc/delete/4,5
Content-Type: application/x-www-form-urlencoded


###
GET http://localhost:8880/redis/set/123/123
Accept: application/json

###
GET http://localhost:8880/redis/get/123
Accept: application/json

